language: ruby

sudo: false

cache: bundler

rvm:
  - 2.0.0
  - 2.1
  - 2.2

addons:
  firefox: "48.0"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: bundle exec ruby headless_rspec.rb
