language: ruby

dist: trusty # required for geckodriver?

sudo: false

cache: bundler

rvm:
  - 2.0.0
  - 2.1
  - 2.2

addons:
  firefox: "48.0"

before_install:
  - GECKODRIVER_URL="https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-linux64.tar.gz";
    FILE=`mktemp`;
    wget "$GECKODRIVER_URL" -qO $FILE && tar xz -C ~ -f $FILE geckodriver;
    rm $FILE;
    chmod 777 ~/geckodriver;
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: bundle exec ruby headless_rspec.rb
